//
// Created by Hans Johnson on 2026-02-14.
//
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "itkBinaryThresholdImageFilter.h"

#include <iostream>
#include <exception>
#include <cstdlib>

#include "SimpleThreshold_sahmed8CLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h

  constexpr unsigned int Dimension = 3;
  using PixelType = short;
  using ImageType = itk::Image<PixelType, Dimension>;
  using ReaderType = itk::ImageFileReader<ImageType>;
  using WriterType = itk::ImageFileWriter<ImageType>;
  using ThresholdFilterType = itk::BinaryThresholdImageFilter<ImageType, ImageType>;

  try {
    if (inputVolume.empty()) {
          std::cerr << "ERROR: --inputVolume is missing." << std::endl;
    }
    if (outputVolume.empty()) {
          std::cerr << "ERROR: --outputVolume is missing." << std::endl;
    }
    if (lowThreshold > highThreshold) {
          std::cerr << "ERROR: lowThreshold must be <= highThreshold." << std::endl;
    }

    std::cout << "The input volume is: " << inputVolume << std::endl;
    std::cout << "The output volume is: " << outputVolume << std::endl;

    auto reader = ReaderType::New();
    reader->SetFileName(inputVolume);

    auto thresholder = ThresholdFilterType::New();
    thresholder->SetInput(reader->GetOutput());
    thresholder->SetLowerThreshold(static_cast<PixelType>(lowThreshold));
    thresholder->SetUpperThreshold(static_cast<PixelType>(highThreshold));
    thresholder->SetOutsideValue(static_cast<PixelType>(outsideValue));
    thresholder->SetInsideValue(static_cast<PixelType>(insideValue));

    auto writer = WriterType::New();
    writer->SetFileName(outputVolume);
    writer->SetInput(thresholder->GetOutput());

    writer->Update();
  }
  catch (const itk::ExceptionObject& err) {
      std::cerr << "ITK exception caught: " << err << std::endl;
      return EXIT_FAILURE;
  }
  catch (const std::exception& err) {
      std::cerr << "Standard exception caught: " << err.what() << std::endl;
      return EXIT_FAILURE;
  }
  catch (...) {
      std::cerr << "Unknown error occurred." << std::endl;
      return EXIT_FAILURE;
  }

  return EXIT_SUCCESS;
}
